# Objective name. It depends on the job type.
# List of possible objective names for each job type: http://77.222.60.131:8080/plugin/moneyhunters/guide/job/creation
BAMBOO:
  # Enables/Disables this objective.
  Enabled: true
  # Min. and max. money amount to drop for this objective.
  # You can use negative values to take money from player's balance.
  Money:
    Min: 0.5
    Max: 5.0
  # Min. and max. exp amount to give for this objective.
  # You can use negative values to take exp from player's job.
  Exp:
    Min: 1
    Max: 3
  # Chance that this objective will drop money and/or exp.
  Chance: 30.0

BEETROOTS:
  Enabled: true
  Chance: 30.0
  Money:
    Min: 0.5
    Max: 5.0
  Exp:
    Min: 1
    Max: 3

CACTUS:
  Enabled: true
  Chance: 30.0
  Money:
    Min: 0.5
    Max: 5.0
  Exp:
    Min: 1
    Max: 3

CARROTS:
  Enabled: true
  Chance: 30.0
  Money:
    Min: 0.5
    Max: 5.0
  Exp:
    Min: 1
    Max: 3

CHORUS_FLOWER:
  Enabled: true
  Chance: 30.0
  Money:
    Min: 0.5
    Max: 5.0
  Exp:
    Min: 1
    Max: 3

COCOA:
  Enabled: true
  Chance: 30.0
  Money:
    Min: 0.5
    Max: 5.0
  Exp:
    Min: 1
    Max: 3

KELP:
  Enabled: true
  Chance: 30.0
  Money:
    Min: 0.5
    Max: 5.0
  Exp:
    Min: 1
    Max: 3

MELON:
  Enabled: true
  Chance: 30.0
  Money:
    Min: 0.5
    Max: 5.0
  Exp:
    Min: 1
    Max: 3

NETHER_WART:
  Enabled: true
  Chance: 30.0
  Money:
    Min: 0.5
    Max: 5.0
  Exp:
    Min: 1
    Max: 3

POTATOES:
  Enabled: true
  Chance: 30.0
  Money:
    Min: 0.5
    Max: 5.0
  Exp:
    Min: 1
    Max: 3

PUMPKIN:
  Enabled: true
  Chance: 30.0
  Money:
    Min: 0.5
    Max: 5.0
  Exp:
    Min: 1
    Max: 3

SUGAR_CANE:
  Enabled: true
  Chance: 30.0
  Money:
    Min: 0.5
    Max: 5.0
  Exp:
    Min: 1
    Max: 3

SWEET_BERRY_BUSH:
  Enabled: true
  Chance: 30.0
  Money:
    Min: 0.5
    Max: 5.0
  Exp:
    Min: 1
    Max: 3

WHEAT:
  Enabled: true
  Chance: 30.0
  Money:
    Min: 0.5
    Max: 5.0
  Exp:
    Min: 1
    Max: 3

