# Objective name. It depends on the job type.
# List of possible objective names for each job type: http://77.222.60.131:8080/plugin/moneyhunters/guide/job/creation
ANDESITE:
  # Enables/Disables this objective.
  Enabled: true
  # Min. and max. money amount to drop for this objective.
  # You can use negative values to take money from player's balance.
  Money:
    Min: 0.5
    Max: 5.0
  # Min. and max. exp amount to give for this objective.
  # You can use negative values to take exp from player's job.
  Exp:
    Min: 1
    Max: 3
  # Chance that this objective will drop money and/or exp.
  Chance: 30.0
  # Objective unlock settings.
  Unlock:
    # Min. player's job level to be able to gain money/exp from this objective.
    Job_Min_Level: 0
  # Objective daily limits for Exp and Money.
  # When player exceed the limit, no money or exp from this objective will be given until the next day.
  # Set to -1 for no limit(s).
  # Scalable. Level placeholder is %job_level%.
  # http://77.222.60.131:8080/plugin/engine/config/formats
  Daily_Limits:
    MONEY: -1.0
    EXP: -1.0
COAL_ORE:
  Enabled: true
  Chance: 30.0
  Money:
    Min: 0.5
    Max: 5.0
  Exp:
    Min: 1
    Max: 3
  Unlock:
    Job_Min_Level: 0
  Daily_Limits:
    MONEY: '-1'
    EXP: '-1'
COBBLESTONE:
  Enabled: true
  Chance: 30.0
  Money:
    Min: 0.5
    Max: 5.0
  Exp:
    Min: 1
    Max: 3
  Unlock:
    Job_Min_Level: 0
  Daily_Limits:
    MONEY: '-1'
    EXP: '-1'
COPPER_ORE:
  Enabled: true
  Chance: 30.0
  Money:
    Min: 0.5
    Max: 5.0
  Exp:
    Min: 1
    Max: 3
  Unlock:
    Job_Min_Level: 0
  Daily_Limits:
    MONEY: '-1'
    EXP: '-1'
DEEPSLATE_COAL_ORE:
  Enabled: true
  Chance: 30.0
  Money:
    Min: 0.5
    Max: 5.0
  Exp:
    Min: 1
    Max: 3
  Unlock:
    Job_Min_Level: 0
  Daily_Limits:
    MONEY: '-1'
    EXP: '-1'
DEEPSLATE_COPPER_ORE:
  Enabled: true
  Chance: 30.0
  Money:
    Min: 0.5
    Max: 5.0
  Exp:
    Min: 1
    Max: 3
  Unlock:
    Job_Min_Level: 0
  Daily_Limits:
    MONEY: '-1'
    EXP: '-1'
DEEPSLATE_DIAMOND_ORE:
  Enabled: true
  Chance: 30.0
  Money:
    Min: 0.5
    Max: 5.0
  Exp:
    Min: 1
    Max: 3
  Unlock:
    Job_Min_Level: 0
  Daily_Limits:
    MONEY: '-1'
    EXP: '-1'
DEEPSLATE_EMERALD_ORE:
  Enabled: true
  Chance: 30.0
  Money:
    Min: 0.5
    Max: 5.0
  Exp:
    Min: 1
    Max: 3
  Unlock:
    Job_Min_Level: 0
  Daily_Limits:
    MONEY: '-1'
    EXP: '-1'
DEEPSLATE_GOLD_ORE:
  Enabled: true
  Chance: 30.0
  Money:
    Min: 0.5
    Max: 5.0
  Exp:
    Min: 1
    Max: 3
  Unlock:
    Job_Min_Level: 0
  Daily_Limits:
    MONEY: '-1'
    EXP: '-1'
DEEPSLATE_IRON_ORE:
  Enabled: true
  Chance: 30.0
  Money:
    Min: 0.5
    Max: 5.0
  Exp:
    Min: 1
    Max: 3
  Unlock:
    Job_Min_Level: 0
  Daily_Limits:
    MONEY: '-1'
    EXP: '-1'
DEEPSLATE_LAPIS_ORE:
  Enabled: true
  Chance: 30.0
  Money:
    Min: 0.5
    Max: 5.0
  Exp:
    Min: 1
    Max: 3
  Unlock:
    Job_Min_Level: 0
  Daily_Limits:
    MONEY: '-1'
    EXP: '-1'
DEEPSLATE_REDSTONE_ORE:
  Enabled: true
  Chance: 30.0
  Money:
    Min: 0.5
    Max: 5.0
  Exp:
    Min: 1
    Max: 3
  Unlock:
    Job_Min_Level: 0
  Daily_Limits:
    MONEY: '-1'
    EXP: '-1'
DIAMOND_ORE:
  Enabled: true
  Chance: 30.0
  Money:
    Min: 0.5
    Max: 5.0
  Exp:
    Min: 1
    Max: 3
  Unlock:
    Job_Min_Level: 0
  Daily_Limits:
    MONEY: '-1'
    EXP: '-1'
DIORITE:
  Enabled: true
  Chance: 30.0
  Money:
    Min: 0.5
    Max: 5.0
  Exp:
    Min: 1
    Max: 3
  Unlock:
    Job_Min_Level: 0
  Daily_Limits:
    MONEY: '-1'
    EXP: '-1'
EMERALD_ORE:
  Enabled: true
  Chance: 30.0
  Money:
    Min: 0.5
    Max: 5.0
  Exp:
    Min: 1
    Max: 3
  Unlock:
    Job_Min_Level: 0
  Daily_Limits:
    MONEY: '-1'
    EXP: '-1'
GOLD_ORE:
  Enabled: true
  Chance: 30.0
  Money:
    Min: 0.5
    Max: 5.0
  Exp:
    Min: 1
    Max: 3
  Unlock:
    Job_Min_Level: 0
  Daily_Limits:
    MONEY: '-1'
    EXP: '-1'
GRANITE:
  Enabled: true
  Chance: 30.0
  Money:
    Min: 0.5
    Max: 5.0
  Exp:
    Min: 1
    Max: 3
  Unlock:
    Job_Min_Level: 0
  Daily_Limits:
    MONEY: '-1'
    EXP: '-1'
IRON_ORE:
  Enabled: true
  Chance: 30.0
  Money:
    Min: 0.5
    Max: 5.0
  Exp:
    Min: 1
    Max: 3
  Unlock:
    Job_Min_Level: 0
  Daily_Limits:
    MONEY: '-1'
    EXP: '-1'
LAPIS_ORE:
  Enabled: true
  Chance: 30.0
  Money:
    Min: 0.5
    Max: 5.0
  Exp:
    Min: 1
    Max: 3
  Unlock:
    Job_Min_Level: 0
  Daily_Limits:
    MONEY: '-1'
    EXP: '-1'
MOSSY_COBBLESTONE:
  Enabled: true
  Chance: 30.0
  Money:
    Min: 0.5
    Max: 5.0
  Exp:
    Min: 1
    Max: 3
  Unlock:
    Job_Min_Level: 0
  Daily_Limits:
    MONEY: '-1'
    EXP: '-1'
NETHERRACK:
  Enabled: true
  Chance: 30.0
  Money:
    Min: 0.5
    Max: 5.0
  Exp:
    Min: 1
    Max: 3
  Unlock:
    Job_Min_Level: 0
  Daily_Limits:
    MONEY: '-1'
    EXP: '-1'
NETHER_GOLD_ORE:
  Enabled: true
  Chance: 30.0
  Money:
    Min: 0.5
    Max: 5.0
  Exp:
    Min: 1
    Max: 3
  Unlock:
    Job_Min_Level: 0
  Daily_Limits:
    MONEY: '-1'
    EXP: '-1'
NETHER_QUARTZ_ORE:
  Enabled: true
  Chance: 30.0
  Money:
    Min: 0.5
    Max: 5.0
  Exp:
    Min: 1
    Max: 3
  Unlock:
    Job_Min_Level: 0
  Daily_Limits:
    MONEY: '-1'
    EXP: '-1'
REDSTONE_ORE:
  Enabled: true
  Chance: 30.0
  Money:
    Min: 0.5
    Max: 5.0
  Exp:
    Min: 1
    Max: 3
  Unlock:
    Job_Min_Level: 0
  Daily_Limits:
    MONEY: '-1'
    EXP: '-1'
STONE:
  Enabled: true
  Chance: 30.0
  Money:
    Min: 0.5
    Max: 5.0
  Exp:
    Min: 1
    Max: 3
  Unlock:
    Job_Min_Level: 0
  Daily_Limits:
    MONEY: '-1'
    EXP: '-1'
